module.exports = {
  baseUrl: "https://localhost:5000/",
  siteName: "NNN Backend",
  jwt_secret: process.env.jwtSecret,
  jwt_expire: "1d",
  Discord_CLIENT_ID: process.env.Discord_CLIENT_ID,
  Discord_CLIENT_SECRET: process.env.Discord_CLIENT_SECRET,
  Discord_redirect: process.env.Discord_redirect,
  Twitter_CLIENT_ID: process.env.Twitter_CLIENT_ID,
  Twitter_CLIENT_SECRET: process.env.Twitter_CLIENT_SECRET,
  Twitter_redirect: process.env.Twitter_redirect,
  DailycheckInRewardInc: process.env.DailycheckInRewardInc,
  ReferrerReward: process.env.ReferrerReward,
  RefereeReward: process.env.RefereeReward,
  TelegramAuthenticationReward: process.env.TelegramAuthenticationReward,
  TwitterAuthenticationReward: process.env.TwitterAuthenticationReward,
  DiscordAuthenticationReward: process.env.DiscordAuthenticationReward,
  QuestEndDate: process.env.QuestEndDate,
};
